### PR TITLE
add support for supplying the filename in the main function

### PR DESCRIPTION
**Pull request by sindresorhus**
@Qix- Can you review?

### CODE REVIEW

**Comment by Qix-** [comment]
Meta-note: did they change the way they show line comments? :-1: 

screen shot 2015-08-31 at 10 17 18 am

**Comment by Qix-** [comment]
Other than those two things, LGTM.

**Comment by sindresorhus** [comment]
> did they change the way they show line comments?

Only if you comment in the commit diff and not the PR diff.

**Comment by Qix-** [comment]
> Only if you comment in the commit diff and not the PR diff.

Oh, weird, I totally did.

**Comment by sindresorhus** [comment]
Thanks for the review.

**Comment by Qix-** [comment]
:+1:

**Pull request closed without merging**
